-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

module(...)

function physicsData(scale)
	local physics = { data =
	{ 
		
		["lvl1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -251, -105.5  ,  -211, -82.5  ,  -229, -53.5  ,  -269, -68.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -192, -111.5  ,  -211, -82.5  ,  -251, -105.5  ,  -220, -144.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -177, -174.5  ,  -159, -136.5  ,  -188, -112.5  ,  -218, -144.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -123, -151.5  ,  -159, -136.5  ,  -177, -174.5  ,  -132, -190.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -48, -150.5  ,  -84, -155.5  ,  -85, -197.5  ,  -37, -192.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -85, -197.5  ,  -84, -155.5  ,  -119, -150.5  ,  -130, -190.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   234, -88.5  ,  259, -58.5  ,  242, -37.5  ,  211, -60.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   282, -77.5  ,  259, -58.5  ,  234, -88.5  ,  259, -106.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   243, -35.5  ,  230, -11.5  ,  192, -27.5  ,  209, -61.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   192, -27.5  ,  230, -11.5  ,  223, 17.5  ,  183, 10.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   64, -112.5  ,  28, -96.5  ,  13, -116.5  ,  41, -145.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   42, -64.5  ,  28, -96.5  ,  64, -112.5  ,  82, -74.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   18, 35.5  ,  33, 17.5  ,  63.7988891601562, 34.68994140625  ,  44, 67.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   63.7988891601562, 34.68994140625  ,  33, 17.5  ,  43, -5.5  ,  82, 4.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -23, 60.5  ,  -2, 51.5  ,  18, 86.5  ,  -13, 101.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   18, 86.5  ,  -2, 51.5  ,  14, 37.5  ,  45, 69.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   10, -117.5  ,  -18, -139.5  ,  7, -171.5  ,  40, -146.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   7, -171.5  ,  -18, -139.5  ,  -46, -151.5  ,  -36, -191.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -45, 103.5  ,  -43, 64.5  ,  -24, 59.5  ,  -14, 100.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -63, 61.5  ,  -43, 64.5  ,  -45, 103.5  ,  -72, 100.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   43, -7.5  ,  45, -34.5  ,  86, -32.5  ,  81, 3.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   86, -32.5  ,  45, -34.5  ,  43, -63.5  ,  83, -70.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -281, -22.5  ,  -236, -14.5  ,  -234, 23.5  ,  -281, 28.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    shape = {   -226, -49.5  ,  -236, -14.5  ,  -281, -22.5  ,  -269, -64.5  }
                    }
                    
                    
                    
		}
		
		, 
		["peg"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535 },
                    radius = 19.000
                    }
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end


